spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mesadeayuda
    username: postgres
    password: os123

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: mesadeayuda
